### ISSUE TITLE
Need help with `canvas` pls

### ISSUE THREAD

**Issue by adamgins** [disney/meteor-base#108]
HI I need some help please

I am using `example/app-with-native-dependencies.dockerfile`

I am getting this error:

```
#16 227.5 > canvas@2.8.0 install /opt/bundle/bundle/programs/server/npm/node_modules/canvas
#16 227.5 > node-pre-gyp install --fallback-to-build
#16 227.5 
#16 227.8 node-pre-gyp WARN Using request for node-pre-gyp https download 
#16 229.2 /bin/sh: pkg-config: not found
#16 229.2 gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
#16 229.2 gyp ERR! configure error 
#16 229.2 gyp ERR! stack Error: `gyp` failed with exit code: 1
#16 229.2 gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
#16 229.2 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#16 229.2 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
#16 229.2 gyp ERR! System Linux 5.10.76-linuxkit
#16 229.2 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/bundle/bundle/programs/server/npm/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/bundle/bundle/programs/server/npm/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
#16 229.2 gyp ERR! cwd /opt/bundle/bundle/programs/server/npm/node_modules/canvas
#16 229.2 gyp ERR! node -v v14.18.3
#16 229.2 gyp ERR! node-gyp -v v5.1.0
#16 229.2 gyp ERR! not ok 
#16 229.2 node-pre-gyp ERR! build error 
#16 229.2 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/bundle/bundle/programs/server/npm/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/bundle/bundle/programs/server/npm/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
#16 229.3 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/bundle/bundle/programs/server/npm/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
#16 229.3 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
#16 229.3 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
#16 229.3 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
#16 229.3 node-pre-gyp ERR! System Linux 5.10.76-linuxkit
#16 229.3 node-pre-gyp ERR! command "/usr/local/bin/node" "/opt/bundle/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#16 229.3 node-pre-gyp ERR! cwd /opt/bundle/bundle/programs/server/npm/node_modules/canvas
#16 229.3 node-pre-gyp ERR! node -v v14.18.3
#16 229.3 node-pre-gyp ERR! node-pre-gyp -v v0.14.0
#16 229.3 node-pre-gyp ERR! not ok 
#16 229.3 Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/bundle/bundle/programs/server/npm/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/bundle/bundle/programs/server/npm/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
#16 229.3 npm ERR! code ELIFECYCLE
#16 229.3 npm ERR! errno 1
#16 229.3 npm ERR! canvas@2.8.0 install: `node-pre-gyp install --fallback-to-build`
#16 229.3 npm ERR! Exit status 1
#16 229.3 npm ERR! 
#16 229.3 npm ERR! Failed at the canvas@2.8.0 install script.
#16 229.3 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#16 229.3 
#16 229.3 npm ERR! A complete log of this run can be found in:
#16 229.3 npm ERR!     /root/.npm/_logs/2022-03-01T02_17_48_156Z-debug.log
------
executor failed running [/bin/sh -c bash $SCRIPTS_FOLDER/build-meteor-npm-dependencies.sh --build-from-source]: exit code: 1
```

in our old `Dockerfile` we had the following 

```
FROM meteor/ubuntu:latest

RUN apt-get update \
    && apt-get install -y \
    libpangocairo-1.0-0 \
    libx11-xcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxi6 \
    libxtst6 \
    libnss3 \
    libcups2 \
    libxss1 \
    libxrandr2 \
    libgconf2-4 \
    libasound2 \
    libatk1.0-0 \
    libgtk-3-0 \
    wget \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /src/*.deb
    
RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64

RUN chmod +x /usr/local/bin/dumb-init

ENTRYPOINT /usr/local/bin/dumb-init -- $METEORD_DIR/run_app.sh
```

Do I just use `apk add <module name>` ?

I did find https://stackoverflow.com/questions/57088230/node-canvas-on-alpine-within-docker

**Comment by adamgins** [comment]
I tried 

```
# The tag here should match the Meteor version of your app, per .meteor/release
FROM geoffreybooth/meteor-base:2.6.1

# Copy app package.json and package-lock.json into container
COPY ./app/package*.json $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh

# Copy app source into container
COPY ./app $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-meteor-bundle.sh


# Use the specific version of Node expected by your Meteor release, per https://docs.meteor.com/changelog.html; this is expected for Meteor 2.6.1
FROM node:14.18.3-alpine

ENV APP_BUNDLE_FOLDER /opt/bundle
ENV SCRIPTS_FOLDER /docker

# Install OS build dependencies, which stay with this intermediate image but don’t become part of the final published image
RUN apk --no-cache add \
	bash \
	g++ \
	make \
	python3

 #  add libraries; sudo so non-root user added downstream can get sudo
RUN apk add --no-cache \
    python3 \
    g++ \
    build-base \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    musl-dev \
    giflib-dev \
    pixman-dev \
    pangomm-dev \
    libjpeg-turbo-dev \
    freetype-dev 
    
RUN	npm install canvas@2.9.0

# Copy in entrypoint
COPY --from=0 $SCRIPTS_FOLDER $SCRIPTS_FOLDER/

# Copy in app bundle
COPY --from=0 $APP_BUNDLE_FOLDER/bundle $APP_BUNDLE_FOLDER/bundle/

RUN bash $SCRIPTS_FOLDER/build-meteor-npm-dependencies.sh --build-from-source


# Start another Docker stage, so that the final image doesn’t contain the layer with the build dependencies
# See previous FROM line; this must match
FROM node:14.18.3-alpine

ENV APP_BUNDLE_FOLDER /opt/bundle
ENV SCRIPTS_FOLDER /docker

# Install OS runtime dependencies
RUN apk --no-cache add \
	bash \
	ca-certificates

# Copy in entrypoint with the built and installed dependencies from the previous image
COPY --from=1 $SCRIPTS_FOLDER $SCRIPTS_FOLDER/

# Copy in app bundle with the built and installed dependencies from the previous image
COPY --from=1 $APP_BUNDLE_FOLDER/bundle $APP_BUNDLE_FOLDER/bundle/

# Start app
ENTRYPOINT ["/docker/entrypoint.sh"]

CMD ["node", "main.js"]
```

but get 

```
"buildUUID":{"uuid":{"$uuid":"1508fc8b-aa1e-4140-9d00-11d6ac329222"}}}}
app_1    | /opt/bundle/bundle/programs/server/node_modules/fibers/future.js:280
app_1    | 						throw(ex);
app_1    | 						^
app_1    | 
app_1    | Error: Error loading shared library libcairo.so.2: No such file or directory (needed by /opt/bundle/bundle/programs/server/npm/node_modules/canvas/build/Release/canvas.node)
app_1    |     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
app_1    |     at Module.load (internal/modules/cjs/loader.js:950:32)
app_1    |     at Module.Mp.load (/opt/bundle/bundle/programs/server/runtime.js:46:33)
app_1    |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
app_1    |     at Module.require (internal/modules/cjs/loader.js:974:19)
app_1    |     at require (internal/modules/cjs/helpers.js:93:18)
app_1    |     at Object.<anonymous> (/opt/bundle/bundle/programs/server/npm/node_modules/canvas/lib/bindings.js:3:18)
app_1    |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
app_1    |     at Module.Mp._compile (/opt/bundle/bundle/programs/server/runtime.js:99:23)
app_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
app_1    |     at Module.load (internal/modules/cjs/loader.js:950:32)
app_1    |     at Module.Mp.load (/opt/bundle/bundle/programs/server/runtime.js:46:33)
app_1    |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
app_1    |     at Module.require (internal/modules/cjs/loader.js:974:19)
app_1    |     at require (internal/modules/cjs/helpers.js:93:18)
app_1    |     at Object.<anonymous> (/opt/bundle/bundle/programs/server/npm/node_modules/canvas/lib/canvas.js:9:18) {
app_1    |   code: 'ERR_DLOPEN_FAILED'
app_1    | }

```

**Comment by GeoffreyBooth** [comment]
You need to update your `Dockerfile` to install the dependencies for `canvas`. This project doesn’t install them for you. See https://github.com/Automattic/node-canvas/issues/1511#:~:text=If%20you%27re%20on%20Alpine%20Linux.
