### ISSUE TITLE
Failing on `build-app-npm-dependencies`

### ISSUE THREAD

**Issue by smeijer** [disney/meteor-base#6]
No idea why, I copied the example file, and on `docker build -t myapp .` the scripts fails on 

```
Sending build context to Docker daemon  23.48MB
Step 1/14 : FROM geoffreybooth/meteor-base:1.7.0.3
 ---> 05c9372eae61
Step 2/14 : COPY ./package*.json $APP_SOURCE_FOLDER/
 ---> Using cache
 ---> 4071b4468bc7
Step 3/14 : RUN bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh
 ---> Running in e3c8917a6feb

[-] Installing app NPM dependencies...

npm ERR! write after end
npm ERR! write after end
npm ERR! write after end
npm ERR! write after end

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-28T18_47_26_273Z-debug.log
The command '/bin/sh -c bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh' returned a non-zero code: 1
```

npm log is not really helping:

```
28079 http fetch GET 200 https://registry.npmjs.org/@babel/parser/-/parser-7.0.0-beta.51.tgz 939ms
28080 http fetch GET 200 https://registry.npmjs.org/@babel/parser/-/parser-7.1.0.tgz 1025ms
28081 http fetch GET 200 https://registry.npmjs.org/ulid/-/ulid-2.3.0.tgz 387ms
28082 http fetch GET 200 https://registry.npmjs.org/wellknown/-/wellknown-0.5.0.tgz 408ms
28083 http fetch GET 200 https://registry.npmjs.org/style 417ms
28084 verbose stack Error: write after end
28084 verbose stack     at writeAfterEnd (_stream_writable.js:236:12)
28084 verbose stack     at PassThrough.Writable.write (_stream_writable.js:287:5)
28084 verbose stack     at PassThrough.Writable.end (_stream_writable.js:563:10)
28084 verbose stack     at ReadEntry.entry.on (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/pacote/lib/extract-stream.js:19:41)
28084 verbose stack     at emitOne (events.js:121:20)
28084 verbose stack     at ReadEntry.emit (events.js:211:7)
28084 verbose stack     at ReadEntry.emit (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/minipass/index.js:309:30)
28084 verbose stack     at ReadEntry.[maybeEmitEnd] (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/minipass/index.js:257:12)
28084 verbose stack     at ReadEntry.end (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/minipass/index.js:167:27)
28084 verbose stack     at Unpack.[consumeBody] (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/pacote/node_modules/tar/lib/parse.js:210:13)
28084 verbose stack     at Unpack.[consumeChunkSub] (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/pacote/node_modules/tar/lib/parse.js:391:40)
28084 verbose stack     at Unpack.[consumeChunk] (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/pacote/node_modules/tar/lib/parse.js:362:30)
28084 verbose stack     at Unzip.(anonymous function).on.chunk (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/pacote/node_modules/tar/lib/parse.js:291:59)
28084 verbose stack     at emitOne (events.js:116:13)
28084 verbose stack     at Unzip.emit (events.js:211:7)
28084 verbose stack     at Unzip.emit (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/minipass/index.js:309:30)
28084 verbose stack     at Unzip.write (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/minipass/index.js:104:17)
28084 verbose stack     at Unzip.write (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/minizlib/index.js:284:29)
28084 verbose stack     at Unpack.write (/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/pacote/node_modules/tar/lib/parse.js:307:19)
28084 verbose stack     at PassThrough.ondata (_stream_readable.js:639:20)
28084 verbose stack     at emitOne (events.js:116:13)
28084 verbose stack     at PassThrough.emit (events.js:211:7)
28085 verbose cwd /opt/src
28086 verbose Linux 4.9.93-linuxkit-aufs
28087 verbose argv "/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/root/.meteor/packages/meteor-tool/.1.7.0_3.u9lhms.hf7k++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "install"
28088 verbose node v8.11.3
28089 verbose npm  v5.10.0
28090 error write after end
28091 verbose exit [ 1, true ]
```

**Comment by GeoffreyBooth** [comment]
There are lots of potential causes for this, that have to do with your dependencies and the version of NPM: https://github.com/npm/npm/issues/19989

You can install a specific version of NPM in the Dockerfile that you copy into your project:

```Dockerfile
FROM geoffreybooth/meteor-base:1.7.0.3
RUN npm install --global npm@latest # Or a specific version
# Rest of Dockerfile as before
```

If it’s caused by one of your dependencies, you can add/remove them one by one until you find which one is causing the issue.

**Comment by smeijer** [comment]
It sounds like it makes a lot of sense, but unfortunately; it doesn't.

The build script is calling `meteor npm install`, and that has nothing to do with the `global npm` version.

Besides that, even if trying, the docker script returns an other error: `/bin/sh: 1: npm: not found`. Which sounds to be quite correct. As we need `meteor npm` to avoid `npm version` problems in the first case.

**Comment by smeijer** [comment]
`meteor npm install --global npm@latest` I tried, and indeed it changed things. Still, something we shouldn't be doing. The whole purpose of `meteor npm` is to have a `npm` version that's guaranteed to work.

At the end, it turned out to indeed be an `npm` / `meteor` issue. Upgrading from meteor `1.7.0.3` to `1.7.0.5` and of course your base image accordingly, fixed the issues.

The issue turned out to be this one: https://github.com/meteor/meteor/issues/9940

Strange thing is that I don't experience it in my normal builds, only in this docker image.

Thanks for the fast replies.
