### ISSUE TITLE
Issue installing bcrypt

### ISSUE THREAD

**Issue by TimHeckel** [disney/meteor-base#99]
Hey all - I'm running a meteor 2.5 app, it's erroring below on the `build-meteor-npm-dependencies.sh --build-from-source` step  - wondering if this has come up for anyone before?

```
 => ERROR [stage-1 5/5] RUN bash /docker/build-meteor-npm-dependencies.sh --build-from-source                                                                                                                           10.9s
------
 > [stage-1 5/5] RUN bash /docker/build-meteor-npm-dependencies.sh --build-from-source:

....
#16 10.69 > bcrypt@5.0.0 install /opt/bundle/bundle/programs/server/npm/node_modules/bcrypt
#16 10.69 > node-pre-gyp install --fallback-to-build
#16 10.69
#16 10.76 internal/modules/cjs/loader.js:905
#16 10.76   throw err;
#16 10.76   ^
#16 10.76
#16 10.76 Error: Cannot find module '../'
#16 10.76 Require stack:
#16 10.76 - /opt/bundle/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp
#16 10.76     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
#16 10.76     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
#16 10.76     at Module.require (internal/modules/cjs/loader.js:974:19)
#16 10.76     at require (internal/modules/cjs/helpers.js:93:18)
#16 10.76     at Object.<anonymous> (/opt/bundle/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp:15:20)
#16 10.76     at Module._compile (internal/modules/cjs/loader.js:1085:14)
#16 10.76     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
#16 10.76     at Module.load (internal/modules/cjs/loader.js:950:32)
#16 10.76     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
#16 10.76     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
#16 10.76   code: 'MODULE_NOT_FOUND',
#16 10.76   requireStack: [
#16 10.76     '/opt/bundle/bundle/programs/server/npm/node_modules/.bin/node-pre-gyp'
#16 10.76   ]
```

**Comment by GeoffreyBooth** [comment]
Have you searched this repo for issues related to bcrypt?

**Comment by TimHeckel** [comment]
Hi - yes I see issues with bcrypt/fibers post meteor 2.5 correlating with M1 architecture, but I'm still running 2.5, not on M1.

I did see an issue where upgrading to bcrypt 5.01 could help - I'll dig further.

**Comment by TimHeckel** [comment]
I upgraded to bcrypt `5.0.1` then ran `docker-compose up --build --force-recreate` and it fixed the issue!

**Comment by red-meadow** [comment]
Hi. It seems that with the latest `accounts-password` version it's not required to include `bcrypt` to `package.json` anymore (thanks to https://github.com/meteor/meteor/pull/11467, I guess). I had a similar issue, so I removed `bcrypt` and used [default.dockerfile](https://github.com/disney/meteor-base/blob/main/example/default.dockerfile) instead of [app-with-native-dependencies.dockerfile](https://github.com/disney/meteor-base/blob/main/example/app-with-native-dependencies.dockerfile), and it helped.
